comandos_comunes = {
    "alias": "Crea o muestra alias de comandos. Ejemplo: alias ll='ls -l' crea un alias 'll' para 'ls -l'.",
    "awk": "Procesa y analiza texto con patrones. Ejemplo: awk '{print $1}' archivo.txt imprime la primera columna.",
    "basename": "Extrae el nombre base de un archivo. Ejemplo: basename /ruta/archivo.txt devuelve 'archivo.txt'.",
    "bg": "Envía un proceso al fondo. Ejemplo: bg %1 reanuda el trabajo 1 en segundo plano.",
    "cat": "Muestra el contenido de archivos o los concatena. Ejemplo: cat archivo.txt muestra 'archivo.txt'.",
    "cd": "Cambia de directorio. Ejemplo: cd dir entra en 'dir'; cd .. retrocede un nivel.",
    "chmod": "Modifica permisos de archivos o directorios. Ejemplo: chmod 755 archivo da permisos completos al dueño.",
    "chown": "Cambia el propietario de archivos o directorios. Ejemplo: chown usuario archivo asigna 'archivo' a 'usuario'.",
    "cp": "Copia archivos o directorios. Ejemplo: cp archivo1 archivo2 copia 'archivo1' a 'archivo2'.",
    "curl": "Transfiere datos desde o hacia un servidor. Ejemplo: curl https://ejemplo.com muestra contenido web.",
    "cut": "Extrae secciones de texto. Ejemplo: cut -d',' -f1 archivo.csv extrae la primera columna.",
    "date": "Muestra o establece fecha y hora. Ejemplo: date muestra la fecha actual.",
    "df": "Muestra uso de espacio en disco. Ejemplo: df -h muestra espacio legible.",
    "diff": "Compara archivos línea por línea. Ejemplo: diff archivo1 archivo2 muestra diferencias.",
    "du": "Muestra uso de espacio de archivos/directorios. Ejemplo: du -sh dir muestra tamaño total.",
    "echo": "Muestra texto en la terminal o redirige a un archivo. Ejemplo: echo 'texto' > archivo.",
    "env": "Muestra o modifica variables de entorno. Ejemplo: env lista variables.",
    "fg": "Trae un proceso al primer plano. Ejemplo: fg %1 reanuda trabajo 1.",
    "file": "Determina tipo de archivo. Ejemplo: file archivo muestra tipo.",
    "find": "Busca archivos y directorios. Ejemplo: find / -name archivo.txt busca en todo el sistema.",
    "free": "Muestra uso de memoria. Ejemplo: free -h muestra memoria legible.",
    "grep": "Busca texto en archivos. Ejemplo: grep 'texto' archivo.txt busca 'texto'.",
    "gzip": "Comprime archivos. Ejemplo: gzip archivo.txt crea archivo.txt.gz.",
    "gunzip": "Descomprime archivos. Ejemplo: gunzip archivo.txt.gz restaura archivo.",
    "head": "Muestra primeras líneas de un archivo. Ejemplo: head -n 5 archivo.txt.",
    "history": "Muestra historial de comandos. Ejemplo: history.",
    "htop": "Muestra procesos en interfaz interactiva. Ejemplo: htop.",
    "id": "Muestra información del usuario actual. Ejemplo: id.",
    "jobs": "Lista trabajos en segundo plano. Ejemplo: jobs.",
    "kill": "Termina procesos. Ejemplo: kill 1234 termina proceso con PID 1234.",
    "less": "Muestra archivos página por página. Ejemplo: less archivo.txt.",
    "ln": "Crea enlaces duros o simbólicos. Ejemplo: ln -s archivo enlace.",
    "ls": "Lista archivos y directorios. Ejemplo: ls -l muestra listado detallado.",
    "man": "Muestra manual de un comando. Ejemplo: man ls.",
    "mkdir": "Crea directorios. Ejemplo: mkdir nombre_directorio.",
    "more": "Muestra archivos página por página. Ejemplo: more archivo.txt.",
    "mv": "Mueve o renombra archivos/directorios. Ejemplo: mv archivo1 archivo2.",
    "nano": "Edita archivos en terminal. Ejemplo: nano archivo.txt.",
    "netstat": "Muestra información de red. Ejemplo: netstat -tulpn.",
    "ping": "Prueba conectividad de red. Ejemplo: ping google.com.",
    "ps": "Muestra procesos en ejecución. Ejemplo: ps aux.",
    "pwd": "Muestra directorio actual. Ejemplo: pwd.",
    "rm": "Elimina archivos o directorios. Ejemplo: rm archivo.",
    "rmdir": "Elimina directorios vacíos. Ejemplo: rmdir directorio.",
    "sed": "Edita texto en archivos. Ejemplo: sed 's/viejo/nuevo/g' archivo.txt.",
    "sort": "Ordena líneas de texto. Ejemplo: sort archivo.txt.",
    "tail": "Muestra últimas líneas de un archivo. Ejemplo: tail -n 5 archivo.txt.",
    "tar": "Archiva o extrae archivos. Ejemplo: tar -cvf archivo.tar dir.",
    "tee": "Lee entrada y escribe en archivo y pantalla. Ejemplo: echo texto | tee archivo.txt.",
    "top": "Muestra procesos en tiempo real. Ejemplo: top.",
    "touch": "Crea archivos vacíos o actualiza fecha. Ejemplo: touch archivo.txt.",
    "uname": "Muestra información del sistema. Ejemplo: uname -a.",
    "uptime": "Muestra tiempo de actividad. Ejemplo: uptime.",
    "whoami": "Muestra el usuario actual. Ejemplo: whoami.",
    "wc": "Cuenta líneas, palabras o caracteres. Ejemplo: wc -l archivo.txt cuenta líneas.",
    "xargs": "Construye y ejecuta comandos desde entrada estándar. Ejemplo: find . -name '*.txt' | xargs rm.",
    "crontab": "Gestiona tareas programadas. Ejemplo: crontab -e edita el archivo crontab.",
    "scp": "Copia archivos entre hosts usando SSH. Ejemplo: scp archivo usuario@host:/ruta.",
    "ssh": "Conecta a un servidor remoto. Ejemplo: ssh usuario@host.",
    "wget": "Descarga archivos desde la web. Ejemplo: wget https://ejemplo.com/archivo.",
    "zip": "Comprime archivos en formato zip. Ejemplo: zip archivo.zip archivo1 archivo2.",
    "unzip": "Descomprime archivos zip. Ejemplo: unzip archivo.zip.",
    "watch": "Ejecuta un comando periódicamente. Ejemplo: watch -n 2 df -h.",
    "which": "Muestra la ruta de un comando. Ejemplo: which ls.",
    "who": "Muestra usuarios conectados. Ejemplo: who.",
    "passwd": "Cambia la contraseña del usuario. Ejemplo: passwd.",
    "sudo": "Ejecuta comandos como superusuario. Ejemplo: sudo apt update.",
    "apt": "Gestiona paquetes en sistemas Debian/Ubuntu. Ejemplo: apt install paquete.",
    "yum": "Gestiona paquetes en sistemas Red Hat/CentOS. Ejemplo: yum install paquete.",
    "dnf": "Gestiona paquetes en Fedora. Ejemplo: dnf install paquete.",
    "journalctl": "Muestra registros del sistema. Ejemplo: journalctl -u servicio.",
    "systemctl": "Controla servicios del sistema. Ejemplo: systemctl start servicio.",
    "ip": "Muestra/configura interfaces de red. Ejemplo: ip addr.",
    "ifconfig": "Muestra/configura interfaces de red (obsoleto). Ejemplo: ifconfig eth0.",
    "rsync": "Sincroniza archivos entre sistemas. Ejemplo: rsync -av dir1/ dir2/.",
    "killall": "Termina procesos por nombre. Ejemplo: killall firefox.",
    "pkill": "Termina procesos por nombre o criterio. Ejemplo: pkill -u usuario.",
    "nohup": "Ejecuta comandos inmunes al cierre de terminal. Ejemplo: nohup script.sh &.",
    "nice": "Establece prioridad de procesos. Ejemplo: nice -n 10 comando.",
    "renice": "Cambia prioridad de procesos en ejecución. Ejemplo: renice 10 -p 1234.",
    "at": "Programa comandos para ejecutarse una vez. Ejemplo: echo 'comando' | at now + 1 hour.",
    "bc": "Calculadora en línea de comandos. Ejemplo: echo '2 + 2' | bc.",
    "expr": "Evalúa expresiones matemáticas. Ejemplo: expr 5 * 3.",
    "test": "Evalúa condiciones en scripts. Ejemplo: test -f archivo.txt.",
    "true": "Devuelve un estado de salida exitoso. Ejemplo: true.",
    "false": "Devuelve un estado de salida fallido. Ejemplo: false.",
    "uniq": "Elimina líneas duplicadas. Ejemplo: uniq archivo.txt.",
    "comm": "Compara dos archivos ordenados. Ejemplo: comm archivo1 archivo2.",
    "paste": "Combina líneas de archivos. Ejemplo: paste archivo1 archivo2.",
    "join": "Une líneas de dos archivos por un campo común. Ejemplo: join archivo1 archivo2.",
    "split": "Divide archivos en partes. Ejemplo: split -l 100 archivo.txt.",
    "dd": "Copia y convierte archivos a bajo nivel. Ejemplo: dd if=entrada of=salida bs=4M.",
    "mkfifo": "Crea tuberías con nombre. Ejemplo: mkfifo tuberia.",
    "time": "Mide tiempo de ejecución de un comando. Ejemplo: time ls.",
    "stat": "Muestra información detallada de archivos. Ejemplo: stat archivo.txt.",
    "chgrp": "Cambia el grupo de archivos/directorios. Ejemplo: chgrp grupo archivo.",
    "getent": "Obtiene entradas de bases de datos del sistema. Ejemplo: getent passwd usuario.",
    "lscpu": "Muestra información de la CPU. Ejemplo: lscpu.",
    "lsblk": "Lista dispositivos de bloque. Ejemplo: lsblk.",
    "dmesg": "Muestra mensajes del kernel. Ejemplo: dmesg | grep error.",
    "adduser": "Agrega un nuevo usuario. Ejemplo: adduser nombre_usuario.",
    "deluser": "Elimina un usuario. Ejemplo: deluser nombre_usuario.",
    "groupadd": "Crea un nuevo grupo. Ejemplo: groupadd nombre_grupo.",
    "groupdel": "Elimina un grupo. Ejemplo: groupdel nombre_grupo.",
    "usermod": "Modifica un usuario existente. Ejemplo: usermod -aG grupo usuario.",
    "useradd": "Crea un usuario nuevo. Ejemplo: useradd nombre_usuario.",
    "userdel": "Elimina un usuario. Ejemplo: userdel nombre_usuario.",
    "chage": "Modifica la expiración de contraseña. Ejemplo: chage -l usuario.",
    "chsh": "Cambia el shell por defecto. Ejemplo: chsh -s /bin/bash.",
    "su": "Cambia de usuario. Ejemplo: su - usuario.",
    "visudo": "Edita el archivo sudoers de forma segura.",
    "last": "Muestra últimos inicios de sesión.",
    "w": "Muestra usuarios conectados y sus procesos.",
    "reboot": "Reinicia el sistema.",
    "shutdown": "Apaga el sistema.",
    "halt": "Detiene el sistema.",
    "poweroff": "Apaga el sistema completamente.",
    "init": "Cambia el nivel de ejecución del sistema.",
    "telinit": "Cambia el nivel de ejecución (similar a init).",
    "fsck": "Chequea y repara sistemas de archivos.",
    "mkfs": "Crea sistemas de archivos.",
    "mount": "Monta sistemas de archivos.",
    "umount": "Desmonta sistemas de archivos.",
    "iotop": "Muestra uso de I/O de discos en tiempo real.",
    "vmstat": "Muestra estadísticas del sistema.",
    "iostat": "Muestra estadísticas de I/O de dispositivos.",
    "sar": "Recolecta, reporta y guarda estadísticas del sistema.",
    "nmon": "Monitor de rendimiento para Linux.",
    "lsof": "Lista archivos abiertos.",
    "strace": "Traza llamadas al sistema.",
    "gdb": "Depurador de programas.",
    "valgrind": "Herramienta para depurar y analizar memoria.",
    "perf": "Herramienta de análisis de rendimiento.",
    "trace-cmd": "Herramienta para trazas del kernel.",
    "nmap": "Escáner de redes y puertos.",
    "netcat": "Herramienta de lectura/escritura en red.",
    "nc": "Alias para netcat.",
    "tcpdump": "Captura paquetes de red.",
    "wireshark": "Analizador de protocolos de red.",
    "iftop": "Monitor de ancho de banda de red.",
    "nethogs": "Monitor de uso de red por proceso.",
    "iptraf": "Herramienta para monitorizar tráfico de red.",
    "dig": "Herramienta para consultas DNS.",
    "nslookup": "Consulta de DNS.",
    "host": "Herramienta para buscar DNS.",
    "whois": "Consulta bases de datos WHOIS.",
    "traceroute": "Muestra ruta hacia un host.",
    "mtr": "Combinación de traceroute y ping.",
    "route": "Muestra/Modifica tabla de rutas IP.",
    "arp": "Muestra/modifica tablas ARP.",
    "ethtool": "Configura interfaces Ethernet.",
    "ss": "Muestra conexiones y sockets.",
    "iwconfig": "Configura interfaces inalámbricas.",
    "iw": "Herramienta para interfaces inalámbricas.",
    "rfkill": "Bloquea/desbloquea dispositivos inalámbricos.",
    "hostname": "Muestra o cambia el nombre del host.",
    "domainname": "Muestra o establece el nombre de dominio.",
    "nisdomainname": "Muestra el nombre de dominio NIS.",
    "ypdomainname": "Muestra el nombre de dominio YP.",
    "logger": "Añade mensajes al syslog.",
    "logrotate": "Rota archivos de log.",
    "cron": "Ejecuta tareas programadas.",
    "anacron": "Ejecuta tareas periódicas con tiempos variables.",
    "batch": "Ejecuta trabajos cuando el sistema está inactivo.",
    "atq": "Lista trabajos pendientes de at.",
    "atrm": "Elimina trabajos de at.",
    "ionice": "Controla prioridad de I/O.",
    "chrt": "Manipula políticas de planificación de procesos.",
    "schedtool": "Configura atributos de planificación.",
    "ulimit": "Configura límites de recursos.",
    "quota": "Muestra límites y uso de cuotas de disco.",
    "quotacheck": "Chequea y repara cuotas de disco.",
    "edquota": "Edita cuotas de disco para usuarios.",
    "repquota": "Reporte de cuotas de disco.",
    "setfacl": "Establece listas de control de acceso.",
    "getfacl": "Muestra listas de control de acceso.",
    "chattr": "Cambia atributos de archivos.",
    "lsattr": "Lista atributos de archivos.",
    "parted": "Herramienta para particionar discos.",
    "fdisk": "Gestor de particiones.",
    "gdisk": "Gestor de particiones GPT.",
    "cfdisk": "Interfaz curses para particiones.",
    "sfdisk": "Herramienta para particionar discos.",
    "mkswap": "Crea espacio de intercambio.",
    "swapon": "Activa espacio de intercambio.",
    "swapoff": "Desactiva espacio de intercambio.",
    "mdadm": "Gestor de arreglos RAID.",
    "lvm": "Gestor de volúmenes lógicos.",
    "pvcreate": "Crea volúmenes físicos para LVM.",
    "vgcreate": "Crea grupos de volúmenes.",
    "lvcreate": "Crea volúmenes lógicos.",
    "pvdisplay": "Muestra información de volúmenes físicos.",
    "vgdisplay": "Muestra información de grupos de volúmenes.",
    "lvdisplay": "Muestra información de volúmenes lógicos.",
    "cryptsetup": "Configura cifrado de discos.",
    "dmsetup": "Herramienta para dispositivos de mapeo.",
    "losetup": "Asocia archivos a dispositivos loop.",
    "blkid": "Muestra información de dispositivos de bloque.",
    "blockdev": "Configura dispositivos de bloque.",
    "hdparm": "Configura parámetros de discos duros.",
    "smartctl": "Controla la salud de discos con SMART.",
    "badblocks": "Busca sectores dañados en discos.",
    "e2fsck": "Chequea sistemas de archivos ext2/3/4.",
    "tune2fs": "Ajusta parámetros de sistemas ext2/3/4.",
    "dumpe2fs": "Muestra información detallada de sistemas ext2/3/4.",
    "resize2fs": "Redimensiona sistemas ext2/3/4.",
    "xfs_repair": "Repara sistemas de archivos XFS.",
    "btrfs": "Gestión de sistemas de archivos btrfs.",
    "zfs": "Gestión de sistemas de archivos ZFS.",
    "fuser": "Muestra procesos que usan archivos o sockets.",
    "pidof": "Muestra PID de procesos.",
    "pstree": "Muestra árbol de procesos.",
    "pmap": "Muestra mapa de memoria de procesos.",
    "slabtop": "Muestra estadísticas de slab allocator.",
    "tmux": "Multiplexor de terminal.",
    "screen": "Multiplexor de terminal clásico.",
    "script": "Graba sesiones de terminal.",
    "scriptreplay": "Reproduce sesiones grabadas.",
    "wall": "Envía mensajes a todos los usuarios.",
    "write": "Envía mensajes a un usuario.",
    "mesg": "Permite o deniega mensajes de terminal.",
    "talk": "Comunicación entre usuarios en terminal.",
    "lastb": "Muestra intentos fallidos de login.",
    "lastlog": "Muestra últimos inicios de sesión por usuario.",
    "faillog": "Muestra intentos fallidos de login.",
    "pam_tally2": "Cuenta intentos de login fallidos.",
    "chfn": "Cambia información del usuario.",
    "newgrp": "Cambia el grupo principal.",
    "sg": "Ejecuta comandos con otro grupo.",
    "groups": "Muestra grupos a los que pertenece un usuario.",
    "nscd": "Daemon de caché de nombres.",
    "rpcinfo": "Muestra servicios RPC registrados.",
    "showmount": "Muestra clientes NFS montados.",
    "exportfs": "Gestiona exportaciones NFS.",
    "nfsstat": "Muestra estadísticas NFS.",
    "smbclient": "Cliente SMB para compartir archivos.",
    "smbstatus": "Muestra estado de SMB.",
    "smbpasswd": "Gestiona contraseñas SMB.",
    "testparm": "Chequea archivos de configuración Samba.",
    "nmblookup": "Busca nombres NetBIOS.",
    "findmnt": "Encuentra puntos de montaje.",
    "lsns": "Muestra namespaces de Linux.",
    "nsenter": "Entra en namespaces de otros procesos.",
    "unshare": "Ejecuta programas en namespaces nuevos.",
    "ipcs": "Muestra IPC activos.",
    "ipcrm": "Elimina IPC.",
    "lsmem": "Muestra información de memoria.",
    "lslogins": "Muestra información de usuarios.",
    "lslocks": "Muestra información de locks.",
    "lsmod": "Muestra módulos cargados.",
    "modprobe": "Carga o elimina módulos del kernel.",
    "insmod": "Inserta módulo en el kernel.",
    "rmmod": "Elimina módulo del kernel.",
    "depmod": "Genera dependencias de módulos.",
    "modinfo": "Muestra información de módulos.",
    "sysctl": "Configura parámetros del kernel en tiempo real.",
    "loginctl": "Controla sesiones de usuario.",
    "machinectl": "Controla máquinas virtuales y contenedores.",
    "systemd-analyze": "Analiza el arranque de systemd.",
    "systemd-cgtop": "Muestra uso de recursos por cgroups.",
    "systemd-escape": "Escapa cadenas para systemd.",
    "systemd-run": "Ejecuta comandos en un servicio systemd.",
    "systemd-tmpfiles": "Gestiona archivos temporales.",
    "systemd-ask-password": "Solicita contraseñas.",
    "locale": "Muestra o cambia configuración regional.",
    "localectl": "Configura locales y teclado.",
    "timedatectl": "Controla fecha y hora.",
    "hostnamectl": "Controla nombre de host.",
    "authconfig": "Configura autenticación.",
    "semanage": "Configura políticas SELinux.",
    "getsebool": "Consulta booleanos SELinux.",
    "setsebool": "Modifica booleanos SELinux.",
    "restorecon": "Restaura contexto SELinux.",
    "chcon": "Cambia contexto SELinux.",
    "auditctl": "Configura auditoría del sistema.",
    "ausearch": "Busca en logs de auditoría.",
    "aureport": "Reporte de auditoría.",
    "semodule": "Gestiona módulos SELinux.",
    "sepolicy": "Herramienta para políticas SELinux.",
    "setroubleshoot": "Ayuda para solucionar problemas SELinux.",
    "aa-status": "Estado de AppArmor.",
    "apparmor_status": "Muestra estado AppArmor.",
    "aa-complain": "Pone perfil AppArmor en modo queja.",
    "aa-enforce": "Pone perfil AppArmor en modo obligatorio.",
    "aa-disable": "Deshabilita perfil AppArmor.",
    "aa-unconfined": "Muestra procesos sin confinamiento AppArmor.",
    "iptables": "Configura firewall con netfilter.",
    "ip6tables": "Configura firewall IPv6.",
    "nft": "Configura firewall con nftables.",
    "firewall-cmd": "Configura firewall de firewalld.",
    "ufw": "Configura firewall sencillo para Ubuntu.",
    "ebtables": "Configura firewall para Ethernet bridges.",
    "arptables": "Configura firewall para ARP.",
    "tc": "Configura control de tráfico de red.",
    "ipset": "Administra conjuntos de IPs para firewall.",
    "fail2ban-client": "Administra Fail2Ban para bloqueo automático.",
    "telnet": "Cliente Telnet para conexión remota.",
    "ftp": "Cliente FTP para transferencia de archivos.",
    "sftp": "Cliente FTP seguro sobre SSH.",
    "rclone": "Herramienta para sincronización de archivos remotos.",
    "curlftpfs": "Monta FTP como sistema de archivos.",
    "sshfs": "Monta sistema de archivos remoto vía SSH.",
    "fusermount": "Desmonta sistemas de archivos FUSE.",
    "findfs": "Encuentra sistemas de archivos.",
    "partprobe": "Actualiza la tabla de particiones.",
    "partx": "Gestiona particiones de dispositivos.",
    "mkfs.ext4": "Crea sistema de archivos ext4.",
    "mkfs.xfs": "Crea sistema de archivos XFS.",
    "mkfs.btrfs": "Crea sistema de archivos BTRFS.",
    "mkfs.vfat": "Crea sistema de archivos FAT.",
    "fsck.ext4": "Chequea sistema de archivos ext4.",
    "fsck.xfs": "Chequea sistema de archivos XFS.",
    "fsck.btrfs": "Chequea sistema de archivos BTRFS.",
    "fsck.vfat": "Chequea sistema de archivos FAT.",
    "xfs_admin": "Administra sistemas de archivos XFS.",
    "pvresize": "Redimensiona volumen físico LVM.",
    "vgextend": "Añade volúmenes físicos a grupo.",
    "lvextend": "Amplía volumen lógico.",
    "lvreduce": "Reduce volumen lógico.",
    "lvs": "Muestra volúmenes lógicos.",
    "vgs": "Muestra grupos de volúmenes.",
    "pvs": "Muestra volúmenes físicos.",
    "raidadm": "Administra arreglos RAID.",
    "mkraid": "Crea arreglos RAID.",
    "drbdadm": "Administra DRBD (bloques replicados).",
    "iscsiadm": "Administra dispositivos iSCSI.",
    "targetcli": "Configura targets iSCSI.",
    "lsscsi": "Lista dispositivos SCSI.",
    "scsi_id": "Muestra identificadores SCSI.",
    "sg_map": "Mapea dispositivos SCSI genéricos.",
    "sg_inq": "Consulta dispositivos SCSI.",
    "sg_readcap": "Muestra capacidad de dispositivos SCSI.",
    "sg_scan": "Escanea dispositivos SCSI.",
    "lshw": "Lista hardware del sistema.",
    "dmidecode": "Muestra información del BIOS y hardware.",
    "lspci": "Lista dispositivos PCI.",
    "lsusb": "Lista dispositivos USB.",
    "lsdev": "Lista dispositivos hardware.",
    "lstopo": "Muestra topología de hardware.",
    "numactl": "Configura afinidad NUMA.",
    "numastat": "Muestra estadísticas NUMA.",
    "taskset": "Configura afinidad de CPU para procesos.",
    "cgroups": "Controla grupos de control.",
    "cgcreate": "Crea cgroups.",
    "cgdelete": "Elimina cgroups.",
    "cgexec": "Ejecuta comandos en cgroups.",
    "cgclassify": "Clasifica procesos en cgroups.",
    "cgget": "Obtiene información de cgroups.",
    "cgset": "Configura cgroups.",
    "systemd-nspawn": "Contenedor ligero systemd.",
    "containerd": "Daemon de contenedores.",
    "docker": "Herramienta de contenedores Docker.",
    "podman": "Alternativa a Docker sin daemon.",
    "buildah": "Construye imágenes de contenedores.",
    "skopeo": "Manipula imágenes de contenedores.",
    "crictl": "Cliente CLI para CRI.",
    "runc": "Ejecuta contenedores OCI.",
    "lxc": "Contenedores Linux.",
    "lxd": "Gestor de contenedores LXC.",
    "virsh": "Administra máquinas virtuales libvirt.",
    "virt-install": "Instala máquinas virtuales.",
    "virt-clone": "Clona máquinas virtuales.",
    "virt-manager": "Interfaz gráfica para virtualización.",
    "qemu-img": "Gestiona imágenes de máquinas virtuales.",
    "qemu-nbd": "Accede a discos de VM vía NBD.",
    "qemu-system-x86_64": "Emulador de sistema x86_64.",
    "kvm": "Virtualización basada en hardware.",
    "xen": "Hipervisor Xen.",
    "xl": "Herramienta de Xen.",
    "xm": "Herramienta antigua de Xen.",
    "virt-what": "Detecta entorno de virtualización.",
    "guestfish": "Herramienta para modificar imágenes VM.",
    "guestmount": "Monta imágenes VM.",
    "libguestfs-test-tool": "Pruebas para libguestfs.",
    "vboxmanage": "Administra VirtualBox.",
    "vagrant": "Automatiza creación de VMs.",
    "ansible": "Automatización de configuraciones.",
    "ansible-playbook": "Ejecuta playbooks Ansible.",
    "puppet": "Automatización de configuraciones.",
    "chef-client": "Cliente de Chef.",
    "salt": "Automatización y configuración.",
    "salt-call": "Ejecuta comandos Salt localmente.",
    "terraform": "Automatiza infraestructura.",
    "packer": "Construye imágenes de máquinas.",
    "vault": "Gestión de secretos.",
    "consul": "Descubrimiento y configuración.",
    "nomad": "Orquestador de trabajos.",
    "etcdctl": "Cliente de etcd.",
    "kubectl": "CLI para Kubernetes.",
    "helm": "Gestor de paquetes para Kubernetes.",
    "minikube": "Kubernetes local para desarrollo.",
    "kind": "Kubernetes en Docker para pruebas.",
    "k3s": "Distribución ligera de Kubernetes.",
    "kubeadm": "Herramienta para configurar Kubernetes.",
    "kompose": "Convierte Docker Compose a Kubernetes.",
    "oc": "CLI para OpenShift.",
    "stern": "Muestra logs de pods Kubernetes.",
    "k9s": "Interfaz terminal para Kubernetes.",
    "lens": "IDE para Kubernetes.",
    "argocd": "GitOps para Kubernetes.",
    "flux": "Automatización GitOps para Kubernetes.",
    "git": "Control de versiones distribuido.",
    "git-clone": "Clona repositorios git.",
    "git-pull": "Actualiza repositorio local.",
    "git-push": "Sube cambios a remoto.",
    "git-commit": "Guarda cambios localmente.",
    "git-merge": "Une ramas git.",
    "git-rebase": "Reaplica commits.",
    "git-checkout": "Cambia ramas o archivos.",
    "git-branch": "Gestiona ramas.",
    "git-tag": "Gestiona etiquetas.",
    "git-log": "Muestra historial de commits.",
    "git-diff": "Muestra diferencias entre versiones.",
    "git-stash": "Guarda cambios temporalmente.",
    "git-reset": "Resetea commits.",
    "git-revert": "Revierte commits.",
    "git-remote": "Gestiona repositorios remotos.",
    "git-fetch": "Descarga objetos remotos.",
    "git-submodule": "Gestiona submódulos.",
    "git-lfs": "Gestiona archivos grandes.",
    "make": "Automatiza compilación de proyectos.",
    "cmake": "Generador de sistemas de construcción.",
    "gcc": "Compilador de C.",
    "g++": "Compilador de C++.",
    "clang": "Compilador alternativo de C.",
    "clang++": "Compilador alternativo de C++.",
    "ld": "Enlaza archivos objeto.",
    "ar": "Crea archivos de biblioteca estática.",
    "ranlib": "Genera índices para bibliotecas.",
    "nm": "Lista símbolos de objetos.",
    "objdump": "Muestra información de objetos.",
    "objcopy": "Copia y convierte archivos objeto.",
    "strip": "Elimina símbolos de depuración.",
    "readelf": "Muestra información de archivos ELF.",
    "lldb": "Depurador LLVM.",
    "ltrace": "Traza llamadas a librerías.",
    "gprof": "Analiza perfiles de ejecución.",
    "gcov": "Cobertura de código.",
    "lcov": "Herramienta para cobertura de código.",
    "cppcheck": "Analizador estático para C/C++.",
    "clang-format": "Formatea código C/C++.",
    "clang-tidy": "Herramienta de linting para C/C++.",
    "astyle": "Formateador de código fuente.",
    "jq": "Procesa JSON.",
    "yq": "Procesa YAML.",
    "xmlstarlet": "Manipula XML.",
    "xmllint": "Valida y procesa XML.",
    "jsonlint": "Valida JSON.",
    "yamllint": "Valida YAML.",
    "shellcheck": "Analiza scripts bash para errores.",
    "shfmt": "Formatea scripts bash.",
    "bats": "Framework para tests bash.",
    "expect": "Automatiza interacciones con programas.",
    "zellij": "Multiplexor de terminal moderno.",
    "byobu": "Multiplexor de terminal mejorado.",
    "btop": "Monitor de recursos moderno.",
    "glances": "Monitor de sistema.",
    "sysstat": "Conjunto de herramientas de monitorización.",
    "dstat": "Muestra estadísticas del sistema en tiempo real.",
    "atop": "Monitor avanzado de sistema.",
    "pidstat": "Monitoriza estadísticas por proceso.",
    "mpstat": "Muestra estadísticas de CPU.",
    "rsyslogd": "Daemon de syslog.",
    "syslog-ng": "Daemon de syslog avanzado.",
    "auditd": "Daemon de auditoría.",
    "fail2ban-client": "Cliente para gestionar Fail2Ban.",
    # Puedes añadir más con sus descripciones aquí si quieres...
}
